# SPDX-FileCopyrightText: 2020-2022, Carles Fernandez-Prades <carles.fernandez@cttc.es>
# SPDX-License-Identifier: MIT

name: Simple CI

on: [push, pull_request]

jobs:
  REUSE-compliance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check REUSE compliance
      uses: docker://fsfe/reuse
      with:
        args: lint

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt install shellcheck
    - name: check script
      run: shellcheck geniux-builder.sh
