# SPDX-FileCopyrightText: 2020-2022, Carles Fernandez-Prades <carles.fernandez@cttc.es>
# SPDX-License-Identifier: MIT

name: Simple CI

on: [push, pull_request]

jobs:
  REUSE-compliance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check REUSE compliance
      uses: docker://fsfe/reuse
      with:
        args: lint

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@master
